[package]
name = "simple_redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
futures="*"
crossbeam = "0.8"

[[example]]
name = "simple_redis_demo"
path = "examples/hello_redis.rs"
